# Generated by Django 4.1.1 on 2022-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_rename_profesion_lector_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
