# Generated by Django 4.1.1 on 2022-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_imagenarticulo_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenarticulo',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
