# Generated by Django 4.1.1 on 2022-11-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
