# Generated by Django 4.1.1 on 2022-11-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0002_rename_nombre_mensaje_remitente_mensaje_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='camada',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
