# Generated by Django 4.1.1 on 2022-11-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_imagenarticulo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='lector',
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
